In [23]:
import pandas as pd

In [73]:
pd.date_range('1-8-2019','31-8-2019',freq='B')#freq='B'-> will only give the data excluding weekends

DatetimeIndex(['2019-01-08', '2019-01-09', '2019-01-10', '2019-01-11',
               '2019-01-14', '2019-01-15', '2019-01-16', '2019-01-17',
               '2019-01-18', '2019-01-21',
               ...
               '2019-08-19', '2019-08-20', '2019-08-21', '2019-08-22',
               '2019-08-23', '2019-08-26', '2019-08-27', '2019-08-28',
               '2019-08-29', '2019-08-30'],
              dtype='datetime64[ns]', length=169, freq='B')

In [42]:
from pandas.tseries.holiday import USFederalHolidayCalendar
from pandas.tseries.offsets import CustomBusinessDay

In [44]:
usb=CustomBusinessDay(calendar=USFederalHolidayCalendar())#<- this guy will give the reults excluding "holidays" and "weekends"

In [59]:
pd.date_range(start='2019-4-1',end='2019-4-30',freq=usb)

DatetimeIndex(['2019-04-01', '2019-04-02', '2019-04-03', '2019-04-04',
               '2019-04-05', '2019-04-08', '2019-04-09', '2019-04-10',
               '2019-04-11', '2019-04-12', '2019-04-15', '2019-04-16',
               '2019-04-17', '2019-04-18', '2019-04-19', '2019-04-22',
               '2019-04-23', '2019-04-24', '2019-04-25', '2019-04-26',
               '2019-04-29', '2019-04-30'],
              dtype='datetime64[ns]', freq='C')

In [60]:
data=pd.read_csv(r'C:\Users\saket\Desktop\DATASETS\No_date_datasets.csv')

In [70]:
data.index=pd.date_range('2019-7-1',periods=len(data.index),freq=usb)

In [72]:
data['2019-7']

           Symbol   Open     High      Low   Close  Volume
2019-07-01   AAAU  15.15  15.1500  15.1500  15.150       0
2019-07-02   AAAU  15.24  15.2750  15.2000  15.250   43100
2019-07-03   AAAU  15.45  15.4900  15.4179  15.450   53400
2019-07-05   AAAU  15.76  15.7658  15.5900  15.620   84800
2019-07-08   AAAU  15.64  15.7000  15.6400  15.680   37000
2019-07-09   AAAU  15.75  15.7500  15.4865  15.560  136600
2019-07-10   AAAU  15.48  15.5100  15.4100  15.465   24600
2019-07-11   AAAU  15.50  15.5700  15.4955  15.570   99000
2019-07-12   AAAU  15.50  15.5100  15.2600  15.450  170800
2019-07-15   AAAU  15.40  15.4400  15.3750  15.435   43400
2019-07-16   AAAU  15.50  15.5400  15.4549  15.520   41700
2019-07-17   AAAU  15.50  15.5001  15.4500  15.490   78100
2019-07-18   AAAU  15.53  15.5800  15.5100  15.530   91600
2019-07-19   AAAU  15.53  15.5300  15.5300  15.530       0
2019-07-22   AAAU  15.45  15.6700  15.4368  15.550  164200
2019-07-23   AAAU  15.54  15.5500  15.5100  15.550   28800
2019-07-24   AAAU  15.54  15.6399  15.5400  15.585  125100
2019-07-25   AAAU  15.56  15.7200  15.5600  15.675   68500
2019-07-26   AAAU  15.80  15.8000  15.7399  15.790   56800
2019-07-29   AAAU  15.72  15.7300  15.6500  15.650   37600
2019-07-30   AAAU  15.65  15.7350  15.6420  15.730   29700
2019-07-31   AAAU  15.76  15.8100  15.6950  15.740   87200